name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["app.py"]'
      env:
        OPEN_API_KEY: ${{ secrets.OpenApiKey }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
