# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - powerpointer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://powerpointer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0ef5f277c3ed497cb46ab65c9b0ac886 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b5cbb17576c6467285055b3913f490d8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: powerpointer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0ef5f277c3ed497cb46ab65c9b0ac886 }}/powerpointer:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'powerpointer'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_eed38f05474945e4bb6f13bd06bc8437 }}
        images: 'powerpointer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0ef5f277c3ed497cb46ab65c9b0ac886 }}/powerpointer:${{ github.sha }}'